[options]
db_name = mydatabase
db_host = localhost
db_port = 5432
db_user = user
db_password = Bakushin!
addons_path = /home/ikec/Documents/Code/odoo-spiel/odoo/addons,/home/ikec/Documents/Code/odoo-spiel/tutorials,/home/ikec/Documents/Code/odoo-spiel/enterprise

